#!/bin/bash
sqlite3 ./database/orderKiosk.db "CREATE TABLE Customer (customer_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, first_name TEXT NOT NULL, last_name TEXT NOT NULL, middle_initial TEXT DEFAULT NULL, phone_num INTEGER NOT NULL, date_join DATE DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TABLE Product (product_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, product_name TEXT NOT NULL UNIQUE, price INTEGER NOT NULL);

CREATE TABLE Topping (topping_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, topping_name TEXT NOT NULL UNIQUE, price INTEGER NOT NULL, extra_price INTEGER NOT NULL);

PRAGMA foreign_keys = ON;

CREATE TABLE CART (cart_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, customer_id INTEGER NOT NULL, date_created DATE DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (customer_id) REFERENCES Customer(customer_id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE SALE(sale_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, cart_id INTEGER NOT NULL UNIQUE, sale_date DATE DEFAULT CURRENT_TIMESTAMP NOT NULL, sale_customer_num INTEGER DEFAULT (ABS(RANDOM() % 500) + 1) NOT NULL, payment_method TEXT NOT NULL, total_price INTEGER NOT NULL, tax_percentage NUMERIC DEFAULT 0.12 NOT NULL, tax INTEGER NOT NULL, tip_percentage NUMERIC NOT NULL, total_tip INTEGER NOT NULL, total_amount INTEGER NOT NULL, sale_completed boolean NOT NULL, FOREIGN KEY(cart_id) REFERENCES Cart(cart_id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE orderItem(order_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, cart_id INTEGER NOT NULL, product_id INTEGER NOT NULL, sugar_level NUMERIC NOT NULL, ice_level TEXT NOT NULL, quantity INTEGER DEFAULT 1 NOT NULL, FOREIGN KEY(cart_id) REFERENCES Cart(cart_id) ON DELETE CASCADE ON UPDATE NO ACTION, FOREIGN KEY(product_id) REFERENCES Product(product_id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE orderTopping(order_id INTEGER NOT NULL, topping_id INTEGER NOT NULL UNIQUE, extra BooLEAN DEFAULT FALSE NOT NULL, PRIMARY KEY(order_id, topping_id), FOREIGN KEY(order_id) REFERENCES orderItem(order_id) ON DELETE CASCADE ON UPDATE NO ACTION, FOREIGN KEY(topping_id) REFERENCES Topping(topping_id) ON DELETE CASCADE ON UPDATE NO ACTION);"
